#!/bin/sh

#sv start socklog-unix || exit 1

export APACHE_LOCK_DIR="/var/run/apache2"
export APACHE_PID_FILE="/var/run/apache2/PID"
export APACHE_RUN_DIR="/var/run/apache2"
export APACHE_LOG_DIR="/var/log/apache2"
export APACHE_RUN_USER="www-data"
export APACHE_RUN_GROUP="www-data"

exec 2>&1
exec /usr/sbin/apache2 -DFOREGROUND
